### ISSUE TITLE
Ensure exact match routes with multiple nested levels are supported

### ISSUE THREAD

**Issue by gemyago** [gemyago/oke-gateway-api#22]
Example route:
```
      matches:
        - path:
            type: Exact
            value: >-
              /.well-known/acme-challenge/VBI-AJ3kw0tC_FvzLlNA058zkNyjtuw0Htc_yJsueNk
```
